### ISSUE TITLE
How to extend node-mysql query prototype to support this feature?

### ISSUE THREAD

**Issue by gajus** [sidorares/named-placeholders#3]
I wonder if anyone has done it?

If not, I will give it a shot and share results.

**Comment by gajus** [comment]
For the record, this is how I have done it:

> ## Named Placeholders
> 
> `mysql` module uses `?` characters as placeholders for values, e.g.
> 
> ```sql
> connection
>     .query('SELECT ?, ?', [
>         'foo',
>         'bar'
>     ]);
> ```
> 
> This example is equivalent to:
> 
> ```sql
> connection.query('SELECT ' + connection.escape('foo') + ', ' + connection.escape('bar'));
> ```
> 
> However, this approach becomes hard to read as query becomes large and the list of values long.
> 
> There is an alternative: named placeholders.
> 
> ```sql
> connection
>     .query('SELECT :foo, :bar', {
>         foo: 'FOO',
>         bar: 'BAR'
>     });
> ```
> 
> The latter is equivalent to:
> 
> ```sql
> connection.query('SELECT ' + connection.escape('FOO') + ', ' + connection.escape('BAR'));
> ```
> 
> Placeholder names can appear multiple times, e.g.
> 
> ```sql
> connection
>     .query('SELECT :foo, :foo', {
>         foo: 'FOO'
>     });
> ```
> 
> The latter is equivalent to:
> 
> ```sql
> connection.query('SELECT ' + connection.escape('FOO') + ', ' + connection.escape('FOO'));
> ```
> 
> As of this writing, `mysql` [does not support named parameters](https://github.com/felixge/node-mysql/issues/920).
> 
> However, it is easy to patch `Connection.prototype.query` prototype to add the support:
> 
> First, you need to install [`named-placeholders`](https://www.npmjs.com/package/named-placeholders) package.
> 
> Then, patch the `Connection.prototype.query`:
> 
> ```js
> const toUnnamed = require('named-placeholders')();
> const originalQuery = require('mysql/lib/Connection').prototype.query;
> 
> require('mysql/lib/Connection').prototype.query = function (...args) {
>     if (Array.isArray(args[0]) || !args[1]) {
>         return originalQuery.apply(this, args);
>     }
> 
>     ([
>         args[0],
>         args[1]
>     ] = toUnnamed(args[0], args[1]));
> 
>     return originalQuery.apply(this, args);
> };
> ```
> 
> That's it. You can now use named placeholders.

From: http://gajus.com/blog/8/using-mysql-in-node-js#named-placeholders

**Comment by pihvi** [comment]
Here's a library for this also supporting ?? syntax:

``` javascript
var sql = require('yesql').mysql

var selectById = sql('SELECT * from ::table_name WHERE id = :id;')
connection.query(selectById({id: 5, table_name: 'pokemon'}), callback)

```
